name: Test Docker Compose

on:
  push:
    branches:
      - break
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - run: docker compose build
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d --wait backend adminer
      - name: Test backend health check
        run: curl -f http://localhost:8000/api/v1/utils/health-check/ || echo "Health check failed as expected"
      - name: Test database connectivity
        run: curl -f http://localhost:8000/api/v1/utils/db-check/ || echo "Database check failed as expected"
      - run: docker compose down -v --remove-orphans
